name: Vault CI/CD

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Vault CLI
      run: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/vault

    - name: Fetch secret from Vault
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: |
        echo "Fetching secret from Vault..."
        export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
        export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
        
        if ! vault kv get -field=username secret/my-secret; then
          echo "Failed to fetch secret."
          exit 1
        fi
        echo "Secret fetched successfully."
